version: "2"

services:
  db:
    image: postgres:9.5
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    image: klaxon
    build: .
    container_name: klaxon
    env_file: .env
    links:
      - db
    depends_on:
      - db
    restart: always
    ports:
      - 80:3000
      - 443:3000

volumes:
  db-data:
    driver: local
