version: "2"

services:
  db:
    image: postgres:9.5
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - default

  app:
    image: klaxon
    build: .
    container_name: klaxon
    env_file: .env
    links:
      - db
    depends_on:
      - db
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "3001:3001"
      - "3004:3004"
    networks:
      - default
      - proxy

volumes:
  db-data:
    driver: local

networks:
  proxy:
    external: true
