version: "2"

services:
  db:
    image: postgres:9.5
    restart: always
    volumes:
      - "db-data:/var/lib/postgresql/data"

  app:
    image: klaxon
    build: .
    container_name: klaxon
    env_file: .env
    links:
      - db
    depends_on:
      - db
    restart: always
    expose:
      - "3000"

  proxy:
    image: nginx
    volumes: # mount custom config at runtime 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - "app:klaxon"
    ports:
      - 80:80
      - 443:80

volumes:
  db-data:
    driver: local